#
#    Copyright 2020 Huawei Technologies Co., Ltd.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#

###spring config####
server:
  port: 30101
  ssl:
    enabled: ${SSL_ENABLED:false}
    key-store: ${SSL_KEY_STORE_PATH:}
    key-store-password: ${SSL_KEY_STORE_PASSWORD:}
    key-store-type: ${SSL_KEY_STORE_TYPE:}
    key-alias: ${SSL_KEY_ALIAS:}
  connection-timeout: 60000
###pgsql config######
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_IP:}:${POSTGRES_PORT:5432}/${POSTGRES_DB_NAME:}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    schema: classpath:reverseproxy.sql
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 5120MB
  mvc:
    async:
      request-timeout: 60000

###mybtis####
mybatis:
  mapper-locations: classpath:mapper/*.xml

security:
  oauth2:
    resource:
      jwt:
        key-uri: ${AUTH_SERVER_ADDRESS:http://user-mgmt-svc:8067}/oauth/token_key

proxy:
  server:
    port:
      min: ${MIN_PROXY_PORT:30111}
      max: ${MAX_PROXY_PORT:30120}
  next-hop:
    port: ${NEXT_HOP_PORT:30210}

signature:
  encrypted-key-path: /usr/app/keys/public.p12
  key-password: ${EDGE_CERT_PASSWORD:Test12345_}

encrypt:
  key-component: ${ENCRYPT_KEY_COMPONENT:edgegallery}